apiVersion: v1
kind: Secret
metadata:
  name: kube-root-ca.crt
type: Opaque
data:
  ca.crt: IyBDb2xlIG8gY29udGXDumRvIGRvIHNldSBjZXJ0aWZpY2FkbyBrdWJlLXJvb3QtY2EuY3J0IGFxdWkuDQojIEV4ZW1wbG86DQojIC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQ0KIyBNSUlGR1RDQ0JBYWdBd0lCQWdJVS4uLg0KIyAtLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t # Substitua pelo conte√∫do do seu certificado codificado em Base64